FROM --platform=linux/amd64 node:22.13-alpine as build

ENV NODE_ENV "development"

WORKDIR /app

# Update npm to the latest version
RUN npm install -g npm@latest

COPY ./examples/frontend/angular .

COPY pkg pkg
# Until pkg is npm copy files and change path to root
RUN rm -rf node_modules package-lock.json
RUN sed -i 's|\"casper-sdk\": \"file:\(\.\.\/\)\+pkg\"|\"casper-sdk\": \"file:pkg\"|' package.json
RUN sed -i 's/"input": "\(\.\.\/\)\+pkg"/\"input": "pkg"/g' project.json

RUN npm install --ignore-scripts --verbose && npm update

# Build proxy from template
RUN npm run build-proxy-conf
# Proxy localhost to gateway
RUN sed -i 's|http://localhost|http://172.17.0.1|g' proxy.conf.json

CMD npm run serve -- --configuration=docker

EXPOSE 4200