FROM --platform=linux/amd64 node:22.1.0-alpine3.19

ENV NODE_ENV "development"

# /dev/rpc network adress (optional)
ENV NODE_ADDRESS "http://localhost:11101"

WORKDIR /app

COPY ./examples/frontend/angular .

COPY pkg pkg

# Until pkg is npm copy files and change path to root
RUN rm package-lock.json
RUN sed -i 's|\"casper-sdk\": \"file:\(\.\.\/\)\+pkg\"|\"casper-sdk\": \"file:pkg\"|' package.json
RUN sed -i 's/"input": "\(\.\.\/\)\+pkg"/\"input": "pkg"/g' project.json

# Build proxy from template
RUN npm run build-proxy-conf
# Proxy localhost to gateway
RUN sed -i 's|http://localhost|http://172.17.0.1|g' proxy.conf.json

RUN npm install --verbose

CMD npm run serve -- --configuration=docker

EXPOSE 4200