services:
  casper-webclient:
    container_name: casper-webclient
    image: casper-webclient-dev:1.6
    build:
      dockerfile: ./docker/Dockerfile.dev
      context: ../
    ports:
      - '4200:4200'
    networks:
      - casper-network

  # Build and run image with Dockerfile
  # docker build -t casper-webclient . --force-rm
  # docker container run -t -i --rm -h casper-webclient -p 4200:4200 casper-webclient

networks:
  casper-network:
    external: false
