services:
  casper-webclient:
    image: interchouette/casper-webclient:latest # Pulls the image from Docker Hub
    container_name: casper-webclient
    ports:
      - "8080:8080"
    environment:
      ENABLE_MCP: ${ENABLE_MCP:-1}
      CASPER_RPC_URL: ${CASPER_RPC_URL:-http://host.docker.internal:11101}
      CASPER_NODE_URL: ${CASPER_NODE_URL:-host.docker.internal:28101}
    networks:
      - casper-network

  cors-anywhere:
    image: interchouette/cors-anywhere:latest # Pulls the image from Docker Hub
    container_name: cors-anywhere
    environment:
      PORT: 11100
      ORIGIN_WHITELIST: |
        http://localhost:8080,
        http://localhost:4200,
        https://localhost:8080,
        https://localhost:4200
    ports:
      - "11100:11100"
    networks:
      - casper-network

  ws-proxy:
    image: interchouette/ws-proxy:latest # Pulls the image from Docker Hub
    container_name: ws-proxy
    environment:
      PORT: 4300
      ALLOWED_HOSTS: |
        localhost,
        127.0.0.1,
        172.18.0.1
      ALLOWED_PORTS: |
        28101,
        7779
    ports:
      - "4300:4300"
    networks:
      - casper-network

networks:
  casper-network:
    external: false
