/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_transferaddr_free(a: number): void;
export function transferaddr_new(a: number, b: number, c: number): void;
export function urefaddr_new(a: number, b: number, c: number): void;
export function __wbg_blockidentifier_free(a: number): void;
export function blockidentifier_new(a: number): number;
export function blockidentifier_from_hash(a: number): number;
export function blockidentifier_fromHeight(a: number): number;
export function blockidentifier_toJson(a: number): number;
export function globalstateidentifier_fromStateRootHash(a: number): number;
export function globalstateidentifier_toJson(a: number): number;
export function __wbg_key_free(a: number): void;
export function key_new(a: number, b: number): void;
export function key_toJson(a: number): number;
export function key_fromURef(a: number): number;
export function key_fromDeployInfo(a: number): number;
export function key_fromAccount(a: number): number;
export function key_fromHash(a: number): number;
export function key_fromTransfer(a: number, b: number): number;
export function key_fromEraInfo(a: number): number;
export function key_fromBalance(a: number): number;
export function key_fromBid(a: number): number;
export function key_fromWithdraw(a: number): number;
export function key_fromDictionaryAddr(a: number): number;
export function key_asDictionaryAddr(a: number): number;
export function key_fromSystemEntityRegistry(): number;
export function key_fromEraSummary(): number;
export function key_fromUnbond(a: number): number;
export function key_fromChainspecRegistry(): number;
export function key_fromChecksumRegistry(): number;
export function key_toFormattedString(a: number, b: number): void;
export function key_fromFormattedString(a: number, b: number, c: number): void;
export function key_fromDictionaryKey(a: number, b: number, c: number): number;
export function key_isDictionaryKey(a: number): number;
export function key_intoAccount(a: number): number;
export function key_intoHash(a: number): number;
export function key_asBalance(a: number): number;
export function key_intoURef(a: number): number;
export function key_urefToHash(a: number): number;
export function key_withdrawToUnbond(a: number): number;
export function __wbg_putdeployresult_free(a: number): void;
export function putdeployresult_api_version(a: number): number;
export function putdeployresult_deploy_hash(a: number): number;
export function putdeployresult_toJson(a: number): number;
export function sdk_deploy(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_getchainspecresult_free(a: number): void;
export function getchainspecresult_api_version(a: number): number;
export function getchainspecresult_chainspec_bytes(a: number): number;
export function getchainspecresult_toJson(a: number): number;
export function sdk_get_chainspec(a: number, b: number, c: number, d: number): number;
export function sdk_info_get_chainspec(a: number, b: number, c: number, d: number): number;
export function __wbg_getaddressableentityresult_free(a: number): void;
export function getaddressableentityresult_api_version(a: number): number;
export function getaddressableentityresult_entity_result(a: number): number;
export function getaddressableentityresult_merkle_proof(a: number, b: number): void;
export function getaddressableentityresult_toJson(a: number): number;
export function __wbg_getentityoptions_free(a: number): void;
export function __wbg_get_getentityoptions_entity_identifier(a: number): number;
export function __wbg_set_getentityoptions_entity_identifier(a: number, b: number): void;
export function __wbg_get_getentityoptions_entity_identifier_as_string(a: number, b: number): void;
export function __wbg_set_getentityoptions_entity_identifier_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getentityoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_getentityoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getentityoptions_maybe_block_identifier(a: number): number;
export function __wbg_set_getentityoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_get_getentityoptions_node_address(a: number, b: number): void;
export function __wbg_set_getentityoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getentityoptions_verbosity(a: number): number;
export function __wbg_set_getentityoptions_verbosity(a: number, b: number): void;
export function sdk_get_entity_options(a: number, b: number, c: number): void;
export function sdk_get_entity(a: number, b: number): number;
export function sdk_state_get_entity(a: number, b: number): number;
export function __wbg_geterainforesult_free(a: number): void;
export function geterainforesult_api_version(a: number): number;
export function geterainforesult_era_summary(a: number): number;
export function geterainforesult_toJson(a: number): number;
export function __wbg_geterainfooptions_free(a: number): void;
export function __wbg_get_geterainfooptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_geterainfooptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_geterainfooptions_node_address(a: number, b: number): void;
export function __wbg_set_geterainfooptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_geterainfooptions_verbosity(a: number): number;
export function __wbg_set_geterainfooptions_verbosity(a: number, b: number): void;
export function sdk_get_era_info_options(a: number, b: number, c: number): void;
export function sdk_get_era_info(a: number, b: number): number;
export function sdk_chain_get_era_info_by_switch_block(a: number, b: number): number;
export function __wbg_getnodestatusresult_free(a: number): void;
export function getnodestatusresult_api_version(a: number): number;
export function getnodestatusresult_chainspec_name(a: number, b: number): void;
export function getnodestatusresult_starting_state_root_hash(a: number): number;
export function getnodestatusresult_peers(a: number): number;
export function getnodestatusresult_last_added_block_info(a: number): number;
export function getnodestatusresult_our_public_signing_key(a: number): number;
export function getnodestatusresult_round_length(a: number): number;
export function getnodestatusresult_next_upgrade(a: number): number;
export function getnodestatusresult_build_version(a: number, b: number): void;
export function getnodestatusresult_uptime(a: number): number;
export function getnodestatusresult_reactor_state(a: number): number;
export function getnodestatusresult_last_progress(a: number): number;
export function getnodestatusresult_available_block_range(a: number): number;
export function getnodestatusresult_block_sync(a: number): number;
export function getnodestatusresult_toJson(a: number): number;
export function sdk_get_node_status(a: number, b: number, c: number, d: number): number;
export function sdk_info_get_status(a: number, b: number, c: number, d: number): number;
export function __wbg_getpeersresult_free(a: number): void;
export function getpeersresult_api_version(a: number): number;
export function getpeersresult_peers(a: number): number;
export function getpeersresult_toJson(a: number): number;
export function sdk_get_peers(a: number, b: number, c: number, d: number): number;
export function sdk_info_get_peers(a: number, b: number, c: number, d: number): number;
export function __wbg_getvalidatorchangesresult_free(a: number): void;
export function getvalidatorchangesresult_api_version(a: number): number;
export function getvalidatorchangesresult_changes(a: number): number;
export function getvalidatorchangesresult_toJson(a: number): number;
export function sdk_get_validator_changes(a: number, b: number, c: number, d: number): number;
export function sdk_info_get_validator_change(a: number, b: number, c: number, d: number): number;
export function __wbg_querybalancedetailsresult_free(a: number): void;
export function querybalancedetailsresult_api_version(a: number): number;
export function querybalancedetailsresult_total_balance(a: number): number;
export function querybalancedetailsresult_available_balance(a: number): number;
export function querybalancedetailsresult_total_balance_proof(a: number): number;
export function querybalancedetailsresult_holds(a: number): number;
export function querybalancedetailsresult_toJson(a: number): number;
export function __wbg_querybalancedetailsoptions_free(a: number): void;
export function __wbg_get_querybalancedetailsoptions_purse_identifier(a: number): number;
export function __wbg_set_querybalancedetailsoptions_purse_identifier(a: number, b: number): void;
export function __wbg_get_querybalancedetailsoptions_global_state_identifier(a: number): number;
export function __wbg_set_querybalancedetailsoptions_global_state_identifier(a: number, b: number): void;
export function __wbg_get_querybalancedetailsoptions_state_root_hash(a: number): number;
export function __wbg_set_querybalancedetailsoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_querybalancedetailsoptions_node_address(a: number, b: number): void;
export function __wbg_set_querybalancedetailsoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_querybalancedetailsoptions_verbosity(a: number): number;
export function __wbg_set_querybalancedetailsoptions_verbosity(a: number, b: number): void;
export function sdk_query_balance_details_options(a: number, b: number, c: number): void;
export function sdk_query_balance_details(a: number, b: number): number;
export function __wbg_queryglobalstateresult_free(a: number): void;
export function queryglobalstateresult_api_version(a: number): number;
export function queryglobalstateresult_block_header(a: number): number;
export function queryglobalstateresult_stored_value(a: number): number;
export function queryglobalstateresult_merkle_proof(a: number, b: number): void;
export function queryglobalstateresult_toJson(a: number): number;
export function __wbg_queryglobalstateoptions_free(a: number): void;
export function __wbg_get_queryglobalstateoptions_global_state_identifier(a: number): number;
export function __wbg_set_queryglobalstateoptions_global_state_identifier(a: number, b: number): void;
export function __wbg_get_queryglobalstateoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_set_queryglobalstateoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_queryglobalstateoptions_state_root_hash(a: number): number;
export function __wbg_set_queryglobalstateoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_queryglobalstateoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_queryglobalstateoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_queryglobalstateoptions_key_as_string(a: number, b: number): void;
export function __wbg_set_queryglobalstateoptions_key_as_string(a: number, b: number, c: number): void;
export function __wbg_get_queryglobalstateoptions_key(a: number): number;
export function __wbg_set_queryglobalstateoptions_key(a: number, b: number): void;
export function __wbg_get_queryglobalstateoptions_path_as_string(a: number, b: number): void;
export function __wbg_set_queryglobalstateoptions_path_as_string(a: number, b: number, c: number): void;
export function __wbg_get_queryglobalstateoptions_path(a: number): number;
export function __wbg_set_queryglobalstateoptions_path(a: number, b: number): void;
export function __wbg_get_queryglobalstateoptions_node_address(a: number, b: number): void;
export function __wbg_set_queryglobalstateoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_queryglobalstateoptions_verbosity(a: number): number;
export function __wbg_set_queryglobalstateoptions_verbosity(a: number, b: number): void;
export function sdk_query_global_state_options(a: number, b: number, c: number): void;
export function sdk_query_global_state(a: number, b: number): number;
export function globalstateidentifier_fromBlockHash(a: number): number;
export function __wbg_set_querybalancedetailsoptions_purse_identifier_as_string(a: number, b: number, c: number): void;
export function __wbg_set_querybalancedetailsoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_set_querybalancedetailsoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function globalstateidentifier_fromBlockHeight(a: number): number;
export function __wbg_get_geterainfooptions_maybe_block_identifier(a: number): number;
export function __wbg_set_geterainfooptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_urefaddr_free(a: number): void;
export function __wbg_globalstateidentifier_free(a: number): void;
export function __wbg_get_querybalancedetailsoptions_purse_identifier_as_string(a: number, b: number): void;
export function __wbg_get_querybalancedetailsoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_get_querybalancedetailsoptions_maybe_block_id_as_string(a: number, b: number): void;
export function globalstateidentifier_new(a: number): number;
export function __wbg_entityidentifier_free(a: number): void;
export function entityidentifier_fromFormattedStr(a: number, b: number, c: number): void;
export function entityidentifier_fromPublicKey(a: number): number;
export function entityidentifier_fromAccountHash(a: number): number;
export function entityidentifier_fromEntityAddr(a: number): number;
export function entityidentifier_toJson(a: number): number;
export function __wbg_path_free(a: number): void;
export function path_new(a: number): number;
export function path_fromArray(a: number): number;
export function path_toJson(a: number): number;
export function path_toString(a: number, b: number): void;
export function path_is_empty(a: number): number;
export function __wbg_transactionstrparams_free(a: number): void;
export function transactionstrparams_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number): number;
export function transactionstrparams_new_with_defaults(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): number;
export function transactionstrparams_secret_key(a: number, b: number): void;
export function transactionstrparams_set_secret_key(a: number, b: number, c: number): void;
export function transactionstrparams_timestamp(a: number, b: number): void;
export function transactionstrparams_set_timestamp(a: number, b: number, c: number): void;
export function transactionstrparams_setDefaultTimestamp(a: number): void;
export function transactionstrparams_ttl(a: number, b: number): void;
export function transactionstrparams_set_ttl(a: number, b: number, c: number): void;
export function transactionstrparams_setDefaultTTL(a: number): void;
export function transactionstrparams_chain_name(a: number, b: number): void;
export function transactionstrparams_set_chain_name(a: number, b: number, c: number): void;
export function transactionstrparams_initiator_addr(a: number, b: number): void;
export function transactionstrparams_set_initiator_addr(a: number, b: number, c: number): void;
export function transactionstrparams_session_args_simple(a: number): number;
export function transactionstrparams_set_session_args_simple(a: number, b: number, c: number): void;
export function transactionstrparams_session_args_json(a: number, b: number): void;
export function transactionstrparams_set_session_args_json(a: number, b: number, c: number): void;
export function transactionstrparams_pricing_mode(a: number): number;
export function transactionstrparams_set_pricing_mode(a: number, b: number): void;
export function transactionstrparams_payment_amount(a: number, b: number): void;
export function transactionstrparams_set_payment_amount(a: number, b: number, c: number): void;
export function transactionstrparams_gas_price_tolerance(a: number, b: number): void;
export function transactionstrparams_set_gas_price_tolerance(a: number, b: number, c: number): void;
export function transactionstrparams_receipt(a: number, b: number): void;
export function transactionstrparams_set_receipt(a: number, b: number, c: number): void;
export function transactionstrparams_standard_payment(a: number): number;
export function transactionstrparams_set_standard_payment(a: number, b: number): void;
export function __wbg_getstateroothashresult_free(a: number): void;
export function getstateroothashresult_api_version(a: number): number;
export function getstateroothashresult_state_root_hash(a: number): number;
export function getstateroothashresult_state_root_hash_as_string(a: number, b: number): void;
export function getstateroothashresult_toString(a: number, b: number): void;
export function getstateroothashresult_toJson(a: number): number;
export function __wbg_getstateroothashoptions_free(a: number): void;
export function __wbg_get_getstateroothashoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_getstateroothashoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getstateroothashoptions_maybe_block_identifier(a: number): number;
export function __wbg_set_getstateroothashoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_get_getstateroothashoptions_node_address(a: number, b: number): void;
export function __wbg_set_getstateroothashoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getstateroothashoptions_verbosity(a: number): number;
export function __wbg_set_getstateroothashoptions_verbosity(a: number, b: number): void;
export function sdk_get_state_root_hash_options(a: number, b: number, c: number): void;
export function sdk_get_state_root_hash(a: number, b: number): number;
export function sdk_chain_get_state_root_hash(a: number, b: number): number;
export function sdk_watchDeploy(a: number, b: number, c: number, d: number, e: number): number;
export function sdk_watchTransaction(a: number, b: number, c: number, d: number, e: number): number;
export function sdk_waitDeploy(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function sdk_waitTransaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_watcher_free(a: number): void;
export function watcher_new(a: number, b: number, c: number, d: number): number;
export function watcher_subscribe(a: number, b: number, c: number, d: number): void;
export function watcher_unsubscribe(a: number, b: number, c: number): void;
export function watcher_start(a: number): number;
export function watcher_stop(a: number): void;
export function __wbg_subscription_free(a: number): void;
export function __wbg_get_subscription_eventHandlerFn(a: number): number;
export function __wbg_set_subscription_eventHandlerFn(a: number, b: number): void;
export function subscription_new(a: number, b: number, c: number): number;
export function __wbg_failure_free(a: number): void;
export function __wbg_get_failure_cost(a: number, b: number): void;
export function __wbg_set_failure_cost(a: number, b: number, c: number): void;
export function __wbg_get_failure_error_message(a: number, b: number): void;
export function __wbg_set_failure_error_message(a: number, b: number, c: number): void;
export function __wbg_version2_free(a: number): void;
export function __wbg_get_version2_error_message(a: number, b: number): void;
export function __wbg_set_version2_error_message(a: number, b: number, c: number): void;
export function __wbg_executionresult_free(a: number): void;
export function __wbg_get_executionresult_Success(a: number): number;
export function __wbg_set_executionresult_Success(a: number, b: number): void;
export function __wbg_get_executionresult_Failure(a: number): number;
export function __wbg_set_executionresult_Failure(a: number, b: number): void;
export function __wbg_hashstring_free(a: number): void;
export function hashstring_toString(a: number, b: number): void;
export function __wbg_messages_free(a: number): void;
export function __wbg_set_messages_entity_hash(a: number, b: number, c: number): void;
export function __wbg_get_messages_message(a: number): number;
export function __wbg_set_messages_message(a: number, b: number): void;
export function __wbg_get_messages_topic_name(a: number, b: number): void;
export function __wbg_set_messages_topic_name(a: number, b: number, c: number): void;
export function __wbg_get_messages_topic_name_hash(a: number, b: number): void;
export function __wbg_set_messages_topic_name_hash(a: number, b: number, c: number): void;
export function __wbg_get_messages_topic_index(a: number): number;
export function __wbg_set_messages_topic_index(a: number, b: number): void;
export function __wbg_get_messages_block_index(a: number): number;
export function __wbg_set_messages_block_index(a: number, b: number): void;
export function __wbg_transactionprocessed_free(a: number): void;
export function __wbg_get_transactionprocessed_hash(a: number): number;
export function __wbg_set_transactionprocessed_hash(a: number, b: number): void;
export function __wbg_get_transactionprocessed_initiator_addr(a: number): number;
export function __wbg_set_transactionprocessed_initiator_addr(a: number, b: number): void;
export function __wbg_get_transactionprocessed_timestamp(a: number, b: number): void;
export function __wbg_set_transactionprocessed_timestamp(a: number, b: number, c: number): void;
export function __wbg_set_transactionprocessed_ttl(a: number, b: number, c: number): void;
export function __wbg_get_transactionprocessed_execution_result(a: number): number;
export function __wbg_set_transactionprocessed_execution_result(a: number, b: number): void;
export function __wbg_get_transactionprocessed_messages(a: number, b: number): void;
export function __wbg_set_transactionprocessed_messages(a: number, b: number, c: number): void;
export function __wbg_body_free(a: number): void;
export function __wbg_get_body_transaction_processed(a: number): number;
export function __wbg_set_body_transaction_processed(a: number, b: number): void;
export function body_get_deploy_processed(a: number): number;
export function __wbg_eventparseresult_free(a: number): void;
export function __wbg_get_eventparseresult_err(a: number, b: number): void;
export function __wbg_set_eventparseresult_err(a: number, b: number, c: number): void;
export function __wbg_get_eventparseresult_body(a: number): number;
export function __wbg_set_eventparseresult_body(a: number, b: number): void;
export function __wbg_set_subscription_targetHash(a: number, b: number, c: number): void;
export function __wbg_set_version2_limit(a: number, b: number, c: number): void;
export function __wbg_set_payment_source(a: number, b: number, c: number): void;
export function __wbg_set_hashstring_hash(a: number, b: number, c: number): void;
export function __wbg_set_publickeystring_PublicKey(a: number, b: number, c: number): void;
export function __wbg_set_message_String(a: number, b: number, c: number): void;
export function __wbg_set_version2_consumed(a: number, b: number, c: number): void;
export function __wbg_set_version2_cost(a: number, b: number, c: number): void;
export function __wbg_set_transactionprocessed_block_hash(a: number, b: number, c: number): void;
export function __wbg_get_version2_initiator(a: number): number;
export function __wbg_set_version2_initiator(a: number, b: number): void;
export function body_get_transaction_processed(a: number): number;
export function __wbg_payment_free(a: number): void;
export function __wbg_publickeystring_free(a: number): void;
export function __wbg_message_free(a: number): void;
export function __wbg_get_subscription_targetHash(a: number, b: number): void;
export function __wbg_get_version2_limit(a: number, b: number): void;
export function __wbg_get_payment_source(a: number, b: number): void;
export function __wbg_get_hashstring_hash(a: number, b: number): void;
export function hashstring_Deploy(a: number, b: number): void;
export function hashstring_Version1(a: number, b: number): void;
export function __wbg_get_publickeystring_PublicKey(a: number, b: number): void;
export function __wbg_get_message_String(a: number, b: number): void;
export function __wbg_get_messages_entity_hash(a: number, b: number): void;
export function __wbg_get_version2_cost(a: number, b: number): void;
export function __wbg_get_version2_consumed(a: number, b: number): void;
export function __wbg_get_transactionprocessed_ttl(a: number, b: number): void;
export function __wbg_get_transactionprocessed_block_hash(a: number, b: number): void;
export function entityidentifier_new_js_alias(a: number, b: number, c: number): void;
export function __wbg_hashaddr_free(a: number): void;
export function hashaddr_new(a: number, b: number, c: number): void;
export function hashaddr_toBytes(a: number, b: number): void;
export function __wbg_bytes_free(a: number): void;
export function bytes_new(): number;
export function bytes_fromUint8Array(a: number): number;
export function __wbg_sessionstrparams_free(a: number): void;
export function sessionstrparams_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number): number;
export function sessionstrparams_session_hash(a: number, b: number): void;
export function sessionstrparams_set_session_hash(a: number, b: number, c: number): void;
export function sessionstrparams_session_name(a: number, b: number): void;
export function sessionstrparams_set_session_name(a: number, b: number, c: number): void;
export function sessionstrparams_session_package_hash(a: number, b: number): void;
export function sessionstrparams_set_session_package_hash(a: number, b: number, c: number): void;
export function sessionstrparams_session_package_name(a: number, b: number): void;
export function sessionstrparams_set_session_package_name(a: number, b: number, c: number): void;
export function sessionstrparams_session_path(a: number, b: number): void;
export function sessionstrparams_set_session_path(a: number, b: number, c: number): void;
export function sessionstrparams_session_bytes(a: number): number;
export function sessionstrparams_set_session_bytes(a: number, b: number): void;
export function sessionstrparams_session_args_simple(a: number): number;
export function sessionstrparams_set_session_args_simple(a: number, b: number): void;
export function sessionstrparams_session_args_json(a: number, b: number): void;
export function sessionstrparams_set_session_args_json(a: number, b: number, c: number): void;
export function sessionstrparams_session_version(a: number, b: number): void;
export function sessionstrparams_set_session_version(a: number, b: number, c: number): void;
export function sessionstrparams_session_entry_point(a: number, b: number): void;
export function sessionstrparams_set_session_entry_point(a: number, b: number, c: number): void;
export function sessionstrparams_is_session_transfer(a: number): number;
export function sessionstrparams_set_is_session_transfer(a: number, b: number): void;
export function __wbg_getbalanceresult_free(a: number): void;
export function getbalanceresult_api_version(a: number): number;
export function getbalanceresult_balance_value(a: number): number;
export function getbalanceresult_merkle_proof(a: number, b: number): void;
export function getbalanceresult_toJson(a: number): number;
export function __wbg_getbalanceoptions_free(a: number): void;
export function __wbg_get_getbalanceoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_set_getbalanceoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getbalanceoptions_state_root_hash(a: number): number;
export function __wbg_set_getbalanceoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_getbalanceoptions_purse_uref_as_string(a: number, b: number): void;
export function __wbg_set_getbalanceoptions_purse_uref_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getbalanceoptions_purse_uref(a: number): number;
export function __wbg_set_getbalanceoptions_purse_uref(a: number, b: number): void;
export function __wbg_get_getbalanceoptions_node_address(a: number, b: number): void;
export function __wbg_set_getbalanceoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getbalanceoptions_verbosity(a: number): number;
export function __wbg_set_getbalanceoptions_verbosity(a: number, b: number): void;
export function sdk_get_balance_options(a: number, b: number, c: number): void;
export function sdk_get_balance(a: number, b: number): number;
export function sdk_state_get_balance(a: number, b: number): number;
export function __wbg_getdictionaryitemresult_free(a: number): void;
export function getdictionaryitemresult_api_version(a: number): number;
export function getdictionaryitemresult_dictionary_key(a: number, b: number): void;
export function getdictionaryitemresult_stored_value(a: number): number;
export function getdictionaryitemresult_merkle_proof(a: number, b: number): void;
export function getdictionaryitemresult_toJson(a: number): number;
export function __wbg_getdictionaryitemoptions_free(a: number): void;
export function __wbg_get_getdictionaryitemoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_set_getdictionaryitemoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getdictionaryitemoptions_state_root_hash(a: number): number;
export function __wbg_set_getdictionaryitemoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_getdictionaryitemoptions_dictionary_item_params(a: number): number;
export function __wbg_set_getdictionaryitemoptions_dictionary_item_params(a: number, b: number): void;
export function __wbg_get_getdictionaryitemoptions_dictionary_item_identifier(a: number): number;
export function __wbg_set_getdictionaryitemoptions_dictionary_item_identifier(a: number, b: number): void;
export function __wbg_get_getdictionaryitemoptions_node_address(a: number, b: number): void;
export function __wbg_set_getdictionaryitemoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getdictionaryitemoptions_verbosity(a: number): number;
export function __wbg_set_getdictionaryitemoptions_verbosity(a: number, b: number): void;
export function sdk_get_dictionary_item_options(a: number, b: number, c: number): void;
export function sdk_get_dictionary_item(a: number, b: number): number;
export function sdk_state_get_dictionary_item(a: number, b: number): number;
export function __wbg_listrpcsresult_free(a: number): void;
export function listrpcsresult_api_version(a: number): number;
export function listrpcsresult_name(a: number, b: number): void;
export function listrpcsresult_schema(a: number): number;
export function listrpcsresult_toJson(a: number): number;
export function sdk_list_rpcs(a: number, b: number, c: number, d: number): number;
export function __wbg_speculativeexecresult_free(a: number): void;
export function speculativeexecresult_api_version(a: number): number;
export function speculativeexecresult_block_hash(a: number): number;
export function speculativeexecresult_execution_result(a: number): number;
export function speculativeexecresult_toJson(a: number): number;
export function __wbg_getspeculativeexecdeployoptions_free(a: number): void;
export function __wbg_get_getspeculativeexecdeployoptions_deploy_as_string(a: number, b: number): void;
export function __wbg_set_getspeculativeexecdeployoptions_deploy_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getspeculativeexecdeployoptions_deploy(a: number): number;
export function __wbg_set_getspeculativeexecdeployoptions_deploy(a: number, b: number): void;
export function __wbg_get_getspeculativeexecdeployoptions_node_address(a: number, b: number): void;
export function __wbg_set_getspeculativeexecdeployoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getspeculativeexecdeployoptions_verbosity(a: number): number;
export function __wbg_set_getspeculativeexecdeployoptions_verbosity(a: number, b: number): void;
export function sdk_get_speculative_exec_deploy_options(a: number, b: number, c: number): void;
export function sdk_speculative_exec_deploy(a: number, b: number): number;
export function __wbg_puttransactionresult_free(a: number): void;
export function puttransactionresult_api_version(a: number): number;
export function puttransactionresult_transaction_hash(a: number): number;
export function puttransactionresult_toJson(a: number): number;
export function sdk_transaction(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function sdk_sign_transaction(a: number, b: number, c: number, d: number): number;
export function sdk_query_contract_dict_options(a: number, b: number, c: number): void;
export function sdk_query_contract_dict(a: number, b: number): number;
export function __wbg_querycontractdictoptions_free(a: number): void;
export function __wbg_set_querycontractdictoptions_state_root_hash(a: number, b: number): void;
export function __wbg_set_querycontractdictoptions_verbosity(a: number, b: number): void;
export function __wbg_set_querycontractdictoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_set_querycontractdictoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_querycontractdictoptions_state_root_hash(a: number): number;
export function __wbg_set_querycontractdictoptions_dictionary_item_params(a: number, b: number): void;
export function __wbg_set_querycontractdictoptions_dictionary_item_identifier(a: number, b: number): void;
export function __wbg_get_querycontractdictoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_get_querycontractdictoptions_node_address(a: number, b: number): void;
export function __wbg_get_querycontractdictoptions_dictionary_item_params(a: number): number;
export function __wbg_get_querycontractdictoptions_dictionary_item_identifier(a: number): number;
export function __wbg_get_querycontractdictoptions_verbosity(a: number): number;
export function __wbg_accounthash_free(a: number): void;
export function accounthash_new_js_alias(a: number, b: number, c: number): void;
export function accounthash_fromFormattedStr(a: number, b: number, c: number): void;
export function accounthash_fromPublicKey(a: number): number;
export function accounthash_toFormattedString(a: number, b: number): void;
export function accounthash_toHexString(a: number, b: number): void;
export function accounthash_fromUint8Array(a: number, b: number): number;
export function accounthash_toJson(a: number): number;
export function addressableentityhash_new_js_alias(a: number, b: number, c: number): void;
export function addressableentityhash_fromFormattedStr(a: number, b: number, c: number): void;
export function addressableentityhash_toFormattedString(a: number, b: number): void;
export function addressableentityhash_fromUint8Array(a: number, b: number): number;
export function blockhash_new_js_alias(a: number, b: number, c: number): void;
export function blockhash_fromDigest(a: number, b: number): void;
export function blockhash_toJson(a: number): number;
export function blockhash_toString(a: number, b: number): void;
export function contractpackagehash_new_js_alias(a: number, b: number, c: number): void;
export function contractpackagehash_fromFormattedStr(a: number, b: number, c: number): void;
export function contractpackagehash_toFormattedString(a: number, b: number): void;
export function contractpackagehash_fromUint8Array(a: number, b: number): number;
export function __wbg_eraid_free(a: number): void;
export function eraid_new(a: number): number;
export function eraid_value(a: number): number;
export function __wbg_peerentry_free(a: number): void;
export function peerentry_node_id(a: number, b: number): void;
export function peerentry_address(a: number, b: number): void;
export function __wbg_transfertarget_free(a: number): void;
export function transfertarget_new(a: number, b: number, c: number, d: number): number;
export function __wbg_transactionbuilderparams_free(a: number): void;
export function transactionbuilderparams_newSession(a: number, b: number): number;
export function transactionbuilderparams_newTransfer(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function transactionbuilderparams_newInvocableEntity(a: number, b: number, c: number): number;
export function transactionbuilderparams_newInvocableEntityAlias(a: number, b: number, c: number, d: number): number;
export function transactionbuilderparams_newPackage(a: number, b: number, c: number, d: number, e: number): number;
export function transactionbuilderparams_newPackageAlias(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function transactionbuilderparams_newAddBid(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function transactionbuilderparams_newDelegate(a: number, b: number, c: number, d: number): number;
export function transactionbuilderparams_newUndelegate(a: number, b: number, c: number, d: number): number;
export function transactionbuilderparams_newRedelegate(a: number, b: number, c: number, d: number, e: number): number;
export function transactionbuilderparams_newWithdrawBid(a: number, b: number, c: number): number;
export function transactionbuilderparams_kind(a: number): number;
export function transactionbuilderparams_set_kind(a: number, b: number): void;
export function transactionbuilderparams_transaction_bytes(a: number): number;
export function transactionbuilderparams_set_transaction_bytes(a: number, b: number): void;
export function transactionbuilderparams_maybe_source(a: number): number;
export function transactionbuilderparams_set_maybe_source(a: number, b: number): void;
export function transactionbuilderparams_target(a: number): number;
export function transactionbuilderparams_set_target(a: number, b: number): void;
export function transactionbuilderparams_amount(a: number, b: number): void;
export function transactionbuilderparams_set_amount(a: number, b: number, c: number): void;
export function transactionbuilderparams_maybe_id(a: number, b: number): void;
export function transactionbuilderparams_set_maybe_id(a: number, b: number): void;
export function transactionbuilderparams_entity_hash(a: number): number;
export function transactionbuilderparams_set_entity_hash(a: number, b: number): void;
export function transactionbuilderparams_entity_alias(a: number, b: number): void;
export function transactionbuilderparams_set_entity_alias(a: number, b: number, c: number): void;
export function transactionbuilderparams_entry_point(a: number, b: number): void;
export function transactionbuilderparams_set_entry_point(a: number, b: number, c: number): void;
export function transactionbuilderparams_package_hash(a: number): number;
export function transactionbuilderparams_set_package_hash(a: number, b: number): void;
export function transactionbuilderparams_package_alias(a: number, b: number): void;
export function transactionbuilderparams_set_package_alias(a: number, b: number, c: number): void;
export function transactionbuilderparams_maybe_entity_version(a: number, b: number): void;
export function transactionbuilderparams_set_maybe_entity_version(a: number, b: number): void;
export function transactionbuilderparams_public_key(a: number): number;
export function transactionbuilderparams_set_public_key(a: number, b: number): void;
export function transactionbuilderparams_delegation_rate(a: number): number;
export function transactionbuilderparams_set_delegation_rate(a: number, b: number): void;
export function transactionbuilderparams_delegator(a: number): number;
export function transactionbuilderparams_set_delegator(a: number, b: number): void;
export function transactionbuilderparams_validator(a: number): number;
export function transactionbuilderparams_set_validator(a: number, b: number): void;
export function transactionbuilderparams_new_validator(a: number): number;
export function transactionbuilderparams_set_new_validator(a: number, b: number): void;
export function transactionbuilderparams_minimum_delegation_amount(a: number, b: number): void;
export function transactionbuilderparams_set_minimum_delegation_amount(a: number, b: number): void;
export function transactionbuilderparams_maximum_delegation_amount(a: number, b: number): void;
export function transactionbuilderparams_set_maximum_delegation_amount(a: number, b: number): void;
export function transactionbuilderparams_transaction_category(a: number): number;
export function transactionbuilderparams_set_transaction_category(a: number, b: number): void;
export function sdk_put_transaction(a: number, b: number, c: number, d: number, e: number): number;
export function sdk_account_put_transaction(a: number, b: number, c: number, d: number, e: number): number;
export function __wbg_querybalanceresult_free(a: number): void;
export function querybalanceresult_api_version(a: number): number;
export function querybalanceresult_balance(a: number): number;
export function querybalanceresult_toJson(a: number): number;
export function __wbg_querybalanceoptions_free(a: number): void;
export function __wbg_get_querybalanceoptions_purse_identifier_as_string(a: number, b: number): void;
export function __wbg_set_querybalanceoptions_purse_identifier_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querybalanceoptions_purse_identifier(a: number): number;
export function __wbg_set_querybalanceoptions_purse_identifier(a: number, b: number): void;
export function __wbg_get_querybalanceoptions_global_state_identifier(a: number): number;
export function __wbg_set_querybalanceoptions_global_state_identifier(a: number, b: number): void;
export function __wbg_get_querybalanceoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_set_querybalanceoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querybalanceoptions_state_root_hash(a: number): number;
export function __wbg_set_querybalanceoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_querybalanceoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_querybalanceoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querybalanceoptions_node_address(a: number, b: number): void;
export function __wbg_set_querybalanceoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_querybalanceoptions_verbosity(a: number): number;
export function __wbg_set_querybalanceoptions_verbosity(a: number, b: number): void;
export function sdk_query_balance_options(a: number, b: number, c: number): void;
export function sdk_query_balance(a: number, b: number): number;
export function sdk_speculative_transfer_transaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function sdk_call_entrypoint_deploy(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function sdk_install(a: number, b: number, c: number, d: number, e: number): number;
export function __wbg_sdk_free(a: number): void;
export function sdk_new(a: number, b: number, c: number): number;
export function sdk_getNodeAddress(a: number, b: number, c: number, d: number): void;
export function sdk_setNodeAddress(a: number, b: number, c: number, d: number): void;
export function sdk_getVerbosity(a: number, b: number): number;
export function sdk_setVerbosity(a: number, b: number, c: number): void;
export function __wbg_addressableentityhash_free(a: number): void;
export function __wbg_blockhash_free(a: number): void;
export function __wbg_contractpackagehash_free(a: number): void;
export function __wbg_accountidentifier_free(a: number): void;
export function accountidentifier_fromFormattedStr(a: number, b: number, c: number): void;
export function accountidentifier_fromPublicKey(a: number): number;
export function accountidentifier_fromAccountHash(a: number): number;
export function accountidentifier_toJson(a: number): number;
export function __wbg_dictionaryitemstrparams_free(a: number): void;
export function dictionaryitemstrparams_new(): number;
export function dictionaryitemstrparams_setAccountNamedKey(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemstrparams_setContractNamedKey(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemstrparams_setEntityNamedKey(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemstrparams_setUref(a: number, b: number, c: number, d: number, e: number): void;
export function dictionaryitemstrparams_setDictionary(a: number, b: number, c: number): void;
export function dictionaryitemstrparams_toJson(a: number): number;
export function __wbg_dictionaryitemidentifier_free(a: number): void;
export function dictionaryitemidentifier_newFromAccountInfo(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemidentifier_newFromContractInfo(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemidentifier_newFromEntityInfo(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function dictionaryitemidentifier_newFromSeedUref(a: number, b: number, c: number, d: number, e: number): void;
export function dictionaryitemidentifier_newFromDictionaryKey(a: number, b: number, c: number): void;
export function dictionaryitemidentifier_toJson(a: number): number;
export function publickey_new_js_alias(a: number, b: number, c: number): void;
export function publickey_fromUint8Array(a: number, b: number, c: number): void;
export function publickey_toAccountHash(a: number): number;
export function publickey_toPurseUref(a: number): number;
export function publickey_toJson(a: number): number;
export function __wbg_uref_free(a: number): void;
export function uref_new_js_alias(a: number, b: number, c: number, d: number): void;
export function uref_fromFormattedStr(a: number, b: number, c: number): void;
export function uref_fromUint8Array(a: number, b: number, c: number): number;
export function uref_toFormattedString(a: number, b: number): void;
export function uref_toJson(a: number): number;
export function sdk_speculative_deploy(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function __wbg_getaccountresult_free(a: number): void;
export function getaccountresult_api_version(a: number): number;
export function getaccountresult_account(a: number): number;
export function getaccountresult_merkle_proof(a: number, b: number): void;
export function getaccountresult_toJson(a: number): number;
export function __wbg_getaccountoptions_free(a: number): void;
export function __wbg_get_getaccountoptions_account_identifier(a: number): number;
export function __wbg_set_getaccountoptions_account_identifier(a: number, b: number): void;
export function __wbg_get_getaccountoptions_account_identifier_as_string(a: number, b: number): void;
export function __wbg_set_getaccountoptions_account_identifier_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getaccountoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_getaccountoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getaccountoptions_maybe_block_identifier(a: number): number;
export function __wbg_set_getaccountoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_get_getaccountoptions_node_address(a: number, b: number): void;
export function __wbg_set_getaccountoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getaccountoptions_verbosity(a: number): number;
export function __wbg_set_getaccountoptions_verbosity(a: number, b: number): void;
export function sdk_get_account_options(a: number, b: number, c: number): void;
export function sdk_get_account(a: number, b: number): number;
export function sdk_state_get_account_info(a: number, b: number): number;
export function __wbg_getauctioninforesult_free(a: number): void;
export function getauctioninforesult_api_version(a: number): number;
export function getauctioninforesult_auction_state(a: number): number;
export function getauctioninforesult_toJson(a: number): number;
export function __wbg_getauctioninfooptions_free(a: number): void;
export function __wbg_get_getauctioninfooptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_getauctioninfooptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getauctioninfooptions_node_address(a: number, b: number): void;
export function __wbg_set_getauctioninfooptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getauctioninfooptions_verbosity(a: number): number;
export function __wbg_set_getauctioninfooptions_verbosity(a: number, b: number): void;
export function sdk_get_auction_info_options(a: number, b: number, c: number): void;
export function sdk_get_auction_info(a: number, b: number): number;
export function sdk_state_get_auction_info_js_alias(a: number, b: number): number;
export function __wbg_getblockresult_free(a: number): void;
export function getblockresult_api_version(a: number): number;
export function getblockresult_block(a: number): number;
export function getblockresult_toJson(a: number): number;
export function sdk_get_block_options(a: number, b: number, c: number): void;
export function sdk_get_block(a: number, b: number): number;
export function sdk_chain_get_block(a: number, b: number): number;
export function __wbg_geterasummaryresult_free(a: number): void;
export function geterasummaryresult_api_version(a: number): number;
export function geterasummaryresult_era_summary(a: number): number;
export function geterasummaryresult_toJson(a: number): number;
export function sdk_get_era_summary_options(a: number, b: number, c: number): void;
export function sdk_get_era_summary(a: number, b: number): number;
export function sdk_chain_get_era_summary(a: number, b: number): number;
export function __wbg_querycontractkeyoptions_free(a: number): void;
export function __wbg_get_querycontractkeyoptions_global_state_identifier(a: number): number;
export function __wbg_set_querycontractkeyoptions_global_state_identifier(a: number, b: number): void;
export function __wbg_get_querycontractkeyoptions_state_root_hash_as_string(a: number, b: number): void;
export function __wbg_set_querycontractkeyoptions_state_root_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querycontractkeyoptions_state_root_hash(a: number): number;
export function __wbg_set_querycontractkeyoptions_state_root_hash(a: number, b: number): void;
export function __wbg_get_querycontractkeyoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_querycontractkeyoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querycontractkeyoptions_contract_key_as_string(a: number, b: number): void;
export function __wbg_set_querycontractkeyoptions_contract_key_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querycontractkeyoptions_contract_key(a: number): number;
export function __wbg_set_querycontractkeyoptions_contract_key(a: number, b: number): void;
export function __wbg_get_querycontractkeyoptions_path_as_string(a: number, b: number): void;
export function __wbg_set_querycontractkeyoptions_path_as_string(a: number, b: number, c: number): void;
export function __wbg_get_querycontractkeyoptions_path(a: number): number;
export function __wbg_set_querycontractkeyoptions_path(a: number, b: number): void;
export function __wbg_get_querycontractkeyoptions_node_address(a: number, b: number): void;
export function __wbg_set_querycontractkeyoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_querycontractkeyoptions_verbosity(a: number): number;
export function __wbg_set_querycontractkeyoptions_verbosity(a: number, b: number): void;
export function sdk_query_contract_key_options(a: number, b: number, c: number): void;
export function sdk_query_contract_key(a: number, b: number): number;
export function hexToString(a: number, b: number, c: number): void;
export function hexToUint8Array(a: number, b: number, c: number): void;
export function uint8ArrayToBytes(a: number): number;
export function motesToCSPR(a: number, b: number, c: number): void;
export function jsonPrettyPrint(a: number, b: number, c: number): void;
export function publicKeyFromSecretKey(a: number, b: number, c: number): void;
export function generateSecretKey(a: number): void;
export function generateSecretKey_secp256k1(a: number): void;
export function accountHashToBase64Key(a: number, b: number, c: number): void;
export function getTimestamp(): number;
export function encodeLowerBlake2b(a: number, b: number): number;
export function makeDictionaryItemKey(a: number, b: number, c: number, d: number): void;
export function __wbg_get_getauctioninfooptions_maybe_block_identifier(a: number): number;
export function __wbg_get_getblockoptions_maybe_block_identifier(a: number): number;
export function __wbg_get_geterasummaryoptions_maybe_block_identifier(a: number): number;
export function __wbg_getblockoptions_free(a: number): void;
export function __wbg_geterasummaryoptions_free(a: number): void;
export function accountidentifier_new(a: number, b: number, c: number): void;
export function __wbg_set_getblockoptions_verbosity(a: number, b: number): void;
export function __wbg_set_geterasummaryoptions_verbosity(a: number, b: number): void;
export function __wbg_set_getblockoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_set_getblockoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_set_geterasummaryoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_set_geterasummaryoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_set_getauctioninfooptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_set_getblockoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_set_geterasummaryoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_publickey_free(a: number): void;
export function __wbg_get_getblockoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_get_getblockoptions_node_address(a: number, b: number): void;
export function __wbg_get_geterasummaryoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_get_geterasummaryoptions_node_address(a: number, b: number): void;
export function __wbg_get_getblockoptions_verbosity(a: number): number;
export function __wbg_get_geterasummaryoptions_verbosity(a: number): number;
export function sdk_transfer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function sdk_speculative_transaction(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function sdk_call_entrypoint(a: number, b: number, c: number, d: number, e: number): number;
export function __wbg_accessrights_free(a: number): void;
export function accessrights_NONE(): number;
export function accessrights_READ(): number;
export function accessrights_WRITE(): number;
export function accessrights_ADD(): number;
export function accessrights_READ_ADD(): number;
export function accessrights_READ_WRITE(): number;
export function accessrights_ADD_WRITE(): number;
export function accessrights_READ_ADD_WRITE(): number;
export function accessrights_new(a: number, b: number): void;
export function accessrights_from_bits(a: number, b: number, c: number): number;
export function accessrights_is_readable(a: number): number;
export function accessrights_is_writeable(a: number): number;
export function accessrights_is_addable(a: number): number;
export function accessrights_is_none(a: number): number;
export function dictionaryaddr_new(a: number, b: number, c: number): void;
export function __wbg_entityaddr_free(a: number): void;
export function entityaddr_fromFormattedStr(a: number, b: number, c: number): void;
export function entityaddr_toFormattedString(a: number, b: number): void;
export function entityaddr_toHexString(a: number, b: number): void;
export function entityaddr_toJson(a: number): number;
export function __wbg_contracthash_free(a: number): void;
export function contracthash_new_js_alias(a: number, b: number, c: number): void;
export function contracthash_fromFormattedStr(a: number, b: number, c: number): void;
export function contracthash_toFormattedString(a: number, b: number): void;
export function contracthash_fromUint8Array(a: number, b: number): number;
export function __wbg_deploy_free(a: number): void;
export function deploy_new(a: number): number;
export function deploy_toJson(a: number): number;
export function deploy_withPaymentAndSession(a: number, b: number, c: number, d: number): void;
export function deploy_withTransfer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function deploy_withTTL(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_withTimestamp(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_withChainName(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_withAccount(a: number, b: number, c: number, d: number): number;
export function deploy_withEntryPointName(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_withHash(a: number, b: number, c: number, d: number): number;
export function deploy_withPackageHash(a: number, b: number, c: number, d: number): number;
export function deploy_withModuleBytes(a: number, b: number, c: number, d: number): number;
export function deploy_withSecretKey(a: number, b: number, c: number): number;
export function deploy_withStandardPayment(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_withPayment(a: number, b: number, c: number, d: number): number;
export function deploy_withSession(a: number, b: number, c: number, d: number): number;
export function deploy_validateDeploySize(a: number): number;
export function deploy_isValid(a: number): number;
export function deploy_hash(a: number): number;
export function deploy_hasValidHash(a: number): number;
export function deploy_isExpired(a: number): number;
export function deploy_sign(a: number, b: number, c: number): number;
export function deploy_approvalsHash(a: number): number;
export function deploy_approvals(a: number): number;
export function deploy_isTransfer(a: number): number;
export function deploy_isStandardPayment(a: number, b: number): number;
export function deploy_isStoredContract(a: number): number;
export function deploy_isStoredContractPackage(a: number): number;
export function deploy_isModuleBytes(a: number): number;
export function deploy_isByName(a: number): number;
export function deploy_byName(a: number, b: number): void;
export function deploy_entryPointName(a: number, b: number): void;
export function deploy_addSignature(a: number, b: number, c: number, d: number, e: number): number;
export function deploy_TTL(a: number, b: number): void;
export function deploy_timestamp(a: number, b: number): void;
export function deploy_chainName(a: number, b: number): void;
export function deploy_account(a: number, b: number): void;
export function deploy_paymentAmount(a: number, b: number, c: number): void;
export function deploy_args(a: number): number;
export function deploy_addArg(a: number, b: number, c: number, d: number, e: number): void;
export function deployhash_new_js_alias(a: number, b: number, c: number): void;
export function deployhash_fromDigest(a: number, b: number): void;
export function deployhash_toJson(a: number): number;
export function deployhash_toString(a: number, b: number): void;
export function __wbg_argssimple_free(a: number): void;
export function __wbg_deploystrparams_free(a: number): void;
export function deploystrparams_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function deploystrparams_secret_key(a: number, b: number): void;
export function deploystrparams_set_secret_key(a: number, b: number, c: number): void;
export function deploystrparams_timestamp(a: number, b: number): void;
export function deploystrparams_set_timestamp(a: number, b: number, c: number): void;
export function deploystrparams_setDefaultTimestamp(a: number): void;
export function deploystrparams_ttl(a: number, b: number): void;
export function deploystrparams_set_ttl(a: number, b: number, c: number): void;
export function deploystrparams_setDefaultTTL(a: number): void;
export function deploystrparams_chain_name(a: number, b: number): void;
export function deploystrparams_set_chain_name(a: number, b: number, c: number): void;
export function deploystrparams_session_account(a: number, b: number): void;
export function deploystrparams_set_session_account(a: number, b: number, c: number): void;
export function deploystrparams_gas_price_tolerance(a: number, b: number): void;
export function deploystrparams_set_gas_price_tolerance(a: number, b: number, c: number): void;
export function __wbg_paymentstrparams_free(a: number): void;
export function paymentstrparams_new(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number): number;
export function paymentstrparams_set_payment_amount(a: number, b: number, c: number): void;
export function paymentstrparams_set_payment_hash(a: number, b: number, c: number): void;
export function paymentstrparams_set_payment_name(a: number, b: number, c: number): void;
export function paymentstrparams_set_payment_package_hash(a: number, b: number, c: number): void;
export function paymentstrparams_set_payment_package_name(a: number, b: number, c: number): void;
export function paymentstrparams_set_payment_path(a: number, b: number, c: number): void;
export function paymentstrparams_payment_args_simple(a: number): number;
export function paymentstrparams_set_payment_args_simple(a: number, b: number): void;
export function paymentstrparams_payment_args_json(a: number, b: number): void;
export function paymentstrparams_set_payment_args_json(a: number, b: number, c: number): void;
export function paymentstrparams_payment_version(a: number, b: number): void;
export function paymentstrparams_set_payment_version(a: number, b: number, c: number): void;
export function paymentstrparams_payment_entry_point(a: number, b: number): void;
export function paymentstrparams_set_payment_entry_point(a: number, b: number, c: number): void;
export function digest_new_js_alias(a: number, b: number, c: number): void;
export function digest_fromString(a: number, b: number, c: number): void;
export function digest_fromRaw(a: number, b: number, c: number): void;
export function digest_toJson(a: number): number;
export function digest_toString(a: number, b: number): void;
export function packagehash_new_js_alias(a: number, b: number, c: number): void;
export function packagehash_fromFormattedStr(a: number, b: number, c: number): void;
export function packagehash_toFormattedString(a: number, b: number): void;
export function packagehash_fromUint8Array(a: number, b: number): number;
export function __wbg_purseidentifier_free(a: number): void;
export function purseidentifier_fromPublicKey(a: number): number;
export function purseidentifier_fromAccountHash(a: number): number;
export function purseidentifier_fromURef(a: number): number;
export function purseidentifier_toJson(a: number): number;
export function __wbg_transaction_free(a: number): void;
export function transaction_new(a: number): number;
export function transaction_toJson(a: number): number;
export function transaction_newSession(a: number, b: number, c: number): void;
export function transaction_newTransfer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function transaction_withTTL(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_withTimestamp(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_withChainName(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_withPublicKey(a: number, b: number, c: number, d: number): number;
export function transaction_withAccountHash(a: number, b: number, c: number, d: number): number;
export function transaction_withEntryPoint(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_withEntityHash(a: number, b: number, c: number, d: number): number;
export function transaction_withPackageHash(a: number, b: number, c: number, d: number): number;
export function transaction_withTransactionBytes(a: number, b: number, c: number, d: number): number;
export function transaction_withSecretKey(a: number, b: number, c: number): number;
export function transaction_withBody(a: number, b: number, c: number, d: number): number;
export function transaction_verify(a: number): number;
export function transaction_hash(a: number): number;
export function transaction_expired(a: number): number;
export function transaction_expires(a: number): number;
export function transaction_signers(a: number): number;
export function transaction_authorization_keys(a: number): number;
export function transaction_sign(a: number, b: number, c: number): number;
export function transaction_approvalsHash(a: number): number;
export function transaction_approvals(a: number): number;
export function transaction_header(a: number): number;
export function transaction_is_native(a: number): number;
export function transaction_is_standard_payment(a: number): number;
export function transaction_session_args(a: number): number;
export function transaction_addSignature(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_entry_point(a: number, b: number): void;
export function transaction_ttl(a: number, b: number): void;
export function transaction_timestamp(a: number, b: number): void;
export function transaction_size_estimate(a: number): number;
export function transaction_chain_name(a: number, b: number): void;
export function transaction_initiator_addr(a: number, b: number): void;
export function transaction_account_hash(a: number): number;
export function transaction_addArg(a: number, b: number, c: number, d: number, e: number): void;
export function transactionhash_new_js_alias(a: number, b: number, c: number): void;
export function transactionhash_fromRaw(a: number, b: number, c: number): void;
export function transactionhash_digest(a: number, b: number): void;
export function transactionhash_toJson(a: number): number;
export function transactionhash_toString(a: number, b: number): void;
export function sdk_speculative_transfer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function __wbg_getblocktransfersresult_free(a: number): void;
export function getblocktransfersresult_api_version(a: number): number;
export function getblocktransfersresult_block_hash(a: number): number;
export function getblocktransfersresult_transfers(a: number): number;
export function getblocktransfersresult_toJson(a: number): number;
export function __wbg_getblocktransfersoptions_free(a: number): void;
export function __wbg_get_getblocktransfersoptions_maybe_block_id_as_string(a: number, b: number): void;
export function __wbg_set_getblocktransfersoptions_maybe_block_id_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getblocktransfersoptions_maybe_block_identifier(a: number): number;
export function __wbg_set_getblocktransfersoptions_maybe_block_identifier(a: number, b: number): void;
export function __wbg_get_getblocktransfersoptions_verbosity(a: number): number;
export function __wbg_set_getblocktransfersoptions_verbosity(a: number, b: number): void;
export function __wbg_get_getblocktransfersoptions_node_address(a: number, b: number): void;
export function __wbg_set_getblocktransfersoptions_node_address(a: number, b: number, c: number): void;
export function sdk_get_block_transfers_options(a: number, b: number, c: number): void;
export function sdk_get_block_transfers(a: number, b: number): number;
export function sdk_chain_get_block_transfers(a: number, b: number): number;
export function __wbg_getdeployresult_free(a: number): void;
export function getdeployresult_api_version(a: number): number;
export function getdeployresult_deploy(a: number): number;
export function getdeployresult_execution_info(a: number): number;
export function getdeployresult_toJson(a: number): number;
export function __wbg_getdeployoptions_free(a: number): void;
export function __wbg_get_getdeployoptions_deploy_hash_as_string(a: number, b: number): void;
export function __wbg_set_getdeployoptions_deploy_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getdeployoptions_deploy_hash(a: number): number;
export function __wbg_set_getdeployoptions_deploy_hash(a: number, b: number): void;
export function __wbg_get_getdeployoptions_finalized_approvals(a: number): number;
export function __wbg_set_getdeployoptions_finalized_approvals(a: number, b: number): void;
export function __wbg_get_getdeployoptions_node_address(a: number, b: number): void;
export function __wbg_set_getdeployoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getdeployoptions_verbosity(a: number): number;
export function __wbg_set_getdeployoptions_verbosity(a: number, b: number): void;
export function sdk_get_deploy_options(a: number, b: number, c: number): void;
export function sdk_get_deploy(a: number, b: number): number;
export function sdk_info_get_deploy(a: number, b: number): number;
export function __wbg_gettransactionresult_free(a: number): void;
export function gettransactionresult_api_version(a: number): number;
export function gettransactionresult_transaction(a: number): number;
export function gettransactionresult_execution_info(a: number): number;
export function gettransactionresult_toJson(a: number): number;
export function __wbg_get_gettransactionoptions_transaction_hash(a: number): number;
export function __wbg_set_gettransactionoptions_transaction_hash(a: number, b: number): void;
export function sdk_get_transaction_options(a: number, b: number, c: number): void;
export function sdk_get_transaction(a: number, b: number): number;
export function sdk_info_get_transaction(a: number, b: number): number;
export function sdk_put_deploy(a: number, b: number, c: number, d: number, e: number): number;
export function sdk_account_put_deploy(a: number, b: number, c: number, d: number, e: number): number;
export function __wbg_speculativeexectxnresult_free(a: number): void;
export function speculativeexectxnresult_api_version(a: number): number;
export function speculativeexectxnresult_block_hash(a: number): number;
export function speculativeexectxnresult_execution_result(a: number): number;
export function speculativeexectxnresult_toJson(a: number): number;
export function __wbg_getspeculativeexectxnoptions_free(a: number): void;
export function __wbg_get_getspeculativeexectxnoptions_transaction_as_string(a: number, b: number): void;
export function __wbg_set_getspeculativeexectxnoptions_transaction_as_string(a: number, b: number, c: number): void;
export function __wbg_get_getspeculativeexectxnoptions_transaction(a: number): number;
export function __wbg_set_getspeculativeexectxnoptions_transaction(a: number, b: number): void;
export function __wbg_get_getspeculativeexectxnoptions_node_address(a: number, b: number): void;
export function __wbg_set_getspeculativeexectxnoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_getspeculativeexectxnoptions_verbosity(a: number): number;
export function __wbg_set_getspeculativeexectxnoptions_verbosity(a: number, b: number): void;
export function sdk_get_speculative_exec_options(a: number, b: number, c: number): void;
export function sdk_speculative_exec(a: number, b: number): number;
export function sdk_transfer_transaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number): number;
export function sdk_make_deploy(a: number, b: number, c: number, d: number, e: number): void;
export function sdk_make_transfer(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function sdk_sign_deploy(a: number, b: number, c: number, d: number): number;
export function sdk_make_transaction(a: number, b: number, c: number, d: number): void;
export function sdk_make_transfer_transaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number): void;
export function sdk_install_deploy(a: number, b: number, c: number, d: number, e: number, f: number, g: number): number;
export function paymentstrparams_payment_amount(a: number, b: number): void;
export function paymentstrparams_payment_hash(a: number, b: number): void;
export function paymentstrparams_payment_name(a: number, b: number): void;
export function paymentstrparams_payment_package_hash(a: number, b: number): void;
export function paymentstrparams_payment_package_name(a: number, b: number): void;
export function paymentstrparams_payment_path(a: number, b: number): void;
export function __wbg_gettransactionoptions_free(a: number): void;
export function __wbg_set_gettransactionoptions_verbosity(a: number, b: number): void;
export function __wbg_set_gettransactionoptions_transaction_hash_as_string(a: number, b: number, c: number): void;
export function __wbg_set_gettransactionoptions_node_address(a: number, b: number, c: number): void;
export function __wbg_get_gettransactionoptions_finalized_approvals(a: number): number;
export function __wbg_set_gettransactionoptions_finalized_approvals(a: number, b: number): void;
export function __wbg_dictionaryaddr_free(a: number): void;
export function __wbg_deployhash_free(a: number): void;
export function __wbg_digest_free(a: number): void;
export function __wbg_packagehash_free(a: number): void;
export function __wbg_transactionhash_free(a: number): void;
export function __wbg_get_gettransactionoptions_transaction_hash_as_string(a: number, b: number): void;
export function __wbg_get_gettransactionoptions_node_address(a: number, b: number): void;
export function __wbg_get_gettransactionoptions_verbosity(a: number): number;
export function __wbg_intounderlyingsink_free(a: number): void;
export function intounderlyingsink_write(a: number, b: number): number;
export function intounderlyingsink_close(a: number): number;
export function intounderlyingsink_abort(a: number, b: number): number;
export function __wbg_intounderlyingsource_free(a: number): void;
export function intounderlyingsource_pull(a: number, b: number): number;
export function intounderlyingsource_cancel(a: number): void;
export function __wbg_intounderlyingbytesource_free(a: number): void;
export function intounderlyingbytesource_type(a: number, b: number): void;
export function intounderlyingbytesource_autoAllocateChunkSize(a: number): number;
export function intounderlyingbytesource_start(a: number, b: number): void;
export function intounderlyingbytesource_pull(a: number, b: number): number;
export function intounderlyingbytesource_cancel(a: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h5800a39458d0c4ed(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he0495010d47b241a(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h0fe03a3c64115ee1(a: number, b: number, c: number, d: number): void;
