name: nightly-scheduled-test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs every day at midnight
    - cron: '0 0 * * *'

jobs:
  nightly-make-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - uses: actions/checkout@v4

      - name: Swatinem cache
        uses: Swatinem/rust-cache@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo-audit
        run: cargo install cargo-audit

      # Replace by above service with docker image of stable dev
      - name: Clone casper-nctl-2-docker repository
        run: |
          git clone https://github.com/gRoussac/casper-nctl-2-docker.git

      - name: Build and start the service
        run: |
          cd casper-nctl-2-docker
          make build-start 2.0
          cd ..

      - name: Wait for the service to be ready
        run: |
          echo "Waiting for the service to be ready on port 11101..."
          for i in {1..30}; do # wait for up to 30 seconds
            if nc -z localhost 11101; then
              echo "Service is up!"
              echo "Wait 45s for nctl to boot and create keys"
              sleep 45  # - name: wait for up to 45 seconds for an era like
              break
            fi
            echo "Waiting..."
            sleep 1
          done

          # Check if the service is still not ready after 30 seconds
          if ! nc -z localhost 11101; then
            echo "Service did not start in time!"
            exit 1
          fi

          echo "Waiting for the service to be ready on http://127.0.0.1:18101/events..."

          for i in {1..30}; do  # Wait for up to 30 seconds
            if curl --silent --max-time 2 http://127.0.0.1:18101/events | grep -q "ApiVersion"; then
              echo "Service is up!"
              break
            fi
            echo "Waiting..."
            sleep 1
          done

          # Final check after timeout
          if ! curl --silent --max-time 2 http://127.0.0.1:18101/events | grep -q "ApiVersion"; then
            echo "Service did not start in time!"
            exit 1
          fi

      # - name: List files in the users directory
      #   run: |
      #     echo "Listing files in the users directory of the service container..."
      #     docker exec ${{ job.services.casper-nctl.id }} ls /app/casper-nctl/assets/net-1/users/

      # - name: List files in user-1 directory
      #   run: |
      #     echo "Listing files in ./assets/users/user-1/:"
      #     ls -la ./casper-nctl-2-docker/assets/users/user-1/

      # WARNING: These accounts, and their private keys, are now publicly known.
      # Any funds sent to them on Mainnet or any other live network WILL BE LOST.
      - name: Set SECRET_KEY_USER_1 and SECRET_KEY_USER_2 environment variables
        run: |
          echo "SECRET_KEY_USER_1=$(sed -n '2p' ./casper-nctl-2-docker/assets/users/user-1/secret_key.pem)" >> $GITHUB_ENV
          echo "SECRET_KEY_USER_2=$(sed -n '2p' ./casper-nctl-2-docker/assets/users/user-2/secret_key.pem)" >> $GITHUB_ENV
          echo "ENABLE_ADDRESSABLE_ENTITY=false" >> $GITHUB_ENV

      - name: Print GITHUB_ENV
        run: |
          echo "Contents of GITHUB_ENV:"
          cat $GITHUB_ENV

      - name: Run cargo audit
        run: cargo audit

      - name: Lint
        run: make check-lint

      - name: Unit Tests
        run: make test

      - name: Integration Tests
        run: make integration-test

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: Build lib for all targets
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --all-targets

      # - name: Slack Notification
      #   uses: ravsamhq/notify-slack-action@4ed28566c2bdcdaee6dca2b46b9666d01b4ed8a4 #v1.10.0
      #   if: always()
      #   with:
      #     status: ${{ job.status }}
      #     notification_title: '*{repo}*'
      #     message_format: '{emoji} *{workflow}* *{status_message}* in <{repo_url}|{repo}@{branch}> on <{commit_url}|{commit_sha}>'
      #     footer: '<{run_url}|View Run>'
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # - name: Fake Commit after 50 days
      #   uses: gautamkrishnar/keepalive-workflow@790c7f09285a59b09bb578c85e271c6ff2af97c4 #v1.1.0
