name: publish-rust-sdk-ts

# Disabled: Wasm packages are not published to npm.
# on:
#   release:
#     types: [created]

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - run: make build

      # - name: Publish pkg to NPM
      #   run: npm publish pkg/ --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Publish pkg-nodejs to NPM
      #   run: npm publish pkg-nodejs/ --access public
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
