---
name: publish-rust-sdk-rs

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable

      - name: Crate Publish
        run: cargo publish --token ${{ secrets.crates_io_token }}
